server:
  port: 0
  tomcat:
    mbeanregistry:
      enabled: true

spring:
  application:
    name: trend-service
  cloud:
    config:
      name: trend-chat-dev, trend-service-dev
  config:
    import:
      - optional:configserver:${CONFIG_SERVER_URI}

user-service:
  url: http://localhost:8081